# Generated by Django 3.0.7 on 2020-09-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cartitemmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
